# Generated by Django 6.0 on 2026-01-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guardians', models.CharField(help_text="Pai/mãe ou 'Responsável próprio'", max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('plan_name', models.CharField(max_length=255)),
                ('lessons_total', models.PositiveSmallIntegerField(default=0)),
                ('lessons_done', models.PositiveSmallIntegerField(default=0)),
                ('pix_key', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('todo', 'A fazer'), ('doing', 'Fazendo'), ('done', 'Concluída')], default='todo', max_length=10)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula, ex: Planejamento,Financeiro', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('pending', 'Pendente'), ('canceled', 'Cancelada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.student')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
