# Generated by Django 6.0 on 2026-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.CharField(blank=True, help_text="Pai/mãe ou 'Responsável próprio'", max_length=255),
        ),
    ]
