# Generated by Django 6.0 on 2026-01-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_guardians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
