# Generated by Django 6.0 on 2026-01-19 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_student_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='active',
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='due_date',
            field=models.DateField(help_text='Vencimento da 1ª parcela'),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='issue_date',
            field=models.DateField(help_text='Data do registro (automática)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='default_due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dia de vencimento padrão (1 a 28)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)]),
        ),
    ]
