# Generated by Django 6.0 on 2026-01-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_billinglog'),
        ('core', '0019_remove_student_active_alter_financialentry_due_date_and_more'),
    ]

    operations = [
    ]
