# Generated by Django 6.0 on 2026-01-20 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20260119_1555'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='ID único do evento no Stripe', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Tipo do evento (ex: invoice.paid, customer.subscription.deleted)', max_length=100)),
                ('processed', models.BooleanField(default=False, help_text='Se o evento já foi processado')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Quando o evento foi processado', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro se houver falha no processamento')),
                ('event_data', models.JSONField(default=dict, help_text='Dados completos do evento (para debug)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento Stripe',
                'verbose_name_plural': 'Eventos Stripe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='core_stripe_event_i_23f379_idx'), models.Index(fields=['event_type', 'processed'], name='core_stripe_event_t_311a9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Mensal'), ('semestral', 'Semestral'), ('annual', 'Anual')], help_text='Plano escolhido', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('canceled', 'Cancelada'), ('past_due', 'Atrasada'), ('unpaid', 'Não paga')], default='pending', help_text='Status da assinatura', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID do cliente no Stripe', max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID da assinatura no Stripe', max_length=255, null=True, unique=True)),
                ('current_period_start', models.DateTimeField(blank=True, help_text='Início do período atual', null=True)),
                ('current_period_end', models.DateTimeField(blank=True, help_text='Fim do período atual', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Cancelar ao fim do período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Usuário da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
