# Generated by Django 6.0 on 2026-01-23 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_daynote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Assinatura'},
        ),
    ]
