# Generated by Django 6.0 on 2026-01-26 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_subscription_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text='ID único do ticket (gerado automaticamente)', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('bug', 'Bug / Erro'), ('ux', 'UX / Layout'), ('payment', 'Pagamento / Assinatura'), ('feature', 'Sugestão'), ('other', 'Outro')], help_text='Categoria do problema', max_length=20)),
                ('impact', models.CharField(choices=[('low', 'Baixo (incômodo)'), ('medium', 'Médio (atrapalha)'), ('high', 'Alto (bloqueia uso)')], help_text='Impacto do problema', max_length=20)),
                ('title', models.CharField(help_text='Título curto do problema', max_length=80)),
                ('description', models.TextField(help_text='Descrição detalhada do problema', max_length=2000)),
                ('page', models.CharField(blank=True, help_text='Página onde o problema foi reportado', max_length=255)),
                ('query', models.CharField(blank=True, help_text='Query string da URL', max_length=500)),
                ('url', models.URLField(blank=True, help_text='URL completa onde o problema foi reportado', max_length=500)),
                ('created_at_local', models.CharField(blank=True, help_text='Timestamp local do cliente (string)', max_length=50)),
                ('timezone', models.CharField(blank=True, help_text='Timezone do cliente', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp do servidor (timezone aware)')),
                ('email_sent', models.BooleanField(default=False, help_text='Se o email foi enviado com sucesso')),
                ('email_error', models.TextField(blank=True, help_text='Erro ao enviar email (se houver)')),
                ('user', models.ForeignKey(help_text='Usuário que criou o ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Suporte',
                'verbose_name_plural': 'Tickets de Suporte',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket_id'], name='core_suppor_ticket__3e2621_idx'), models.Index(fields=['user', 'created_at'], name='core_suppor_user_id_63299c_idx'), models.Index(fields=['category', 'impact'], name='core_suppor_categor_eee025_idx')],
            },
        ),
    ]
