# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_teacher',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_students',
                to=settings.AUTH_USER_MODEL,
                help_text='Professor parceiro que dará as aulas (opcional). Definido pelo dono da conta.',
            ),
        ),
    ]
