# Generated by Django 6.0 on 2026-02-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('semestral', 'Semestral'), ('annual', 'Anual')], help_text='Periodicidade do plano (Mensal, Semestral, Anual)', max_length=20),
        ),
    ]
