# Generated by Django 6.0 on 2026-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_userprofile_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='plan_name',
            field=models.CharField(blank=True, help_text='Plano do aluno (pacote)', max_length=255),
        ),
    ]
