# Generated by Django 6.0 on 2026-03-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_student_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher_notes',
            field=models.TextField(blank=True, default='', help_text='Observações do professor sobre o aluno (visível na ficha do aluno)', null=True),
        ),
    ]
