# Generated by Django 6.0 on 2026-03-20
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_studenthomeworkmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentHomeworkMessageRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="core.studenthomeworkmessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_homework_message_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-read_at", "-id"],
                "unique_together": {("message", "user")},
                "verbose_name": "Mensagem da Tarefa do Aluno (Lida)",
                "verbose_name_plural": "Mensagens das Tarefas dos Alunos (Lidas)",
            },
        ),
    ]

