# Generated by Django 6.0.3 on 2026-03-25 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_userprofile_google_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome/título do material exibido na biblioteca', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Descrição ou observação interna (não visível ao aluno)')),
                ('material_type', models.CharField(choices=[('file', 'Arquivo'), ('link', 'Link')], default='file', max_length=10)),
                ('file', models.FileField(blank=True, help_text="Arquivo (preenchido quando material_type='file')", null=True, upload_to='teacher_materials/%Y/%m/')),
                ('external_url', models.URLField(blank=True, default='', help_text="URL externa (preenchida quando material_type='link')")),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Tamanho do arquivo em bytes (0 para links)')),
                ('tags', models.CharField(blank=True, default='', help_text='Tags de organização separadas por vírgula (ex: gramática,B2,speaking)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Professor dono deste material', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material do Professor',
                'verbose_name_plural': 'Materiais do Professor',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
