# Generated by Django 6.0.3 on 2026-03-25 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_task_add_teacher_material'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título interno da campanha (não aparece no email)', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado')], default='draft', max_length=20)),
                ('subject', models.CharField(help_text='Assunto do email', max_length=255)),
                ('preview_text', models.CharField(blank=True, help_text='Pre-header (texto oculto)', max_length=200)),
                ('feature_name', models.CharField(help_text='Nome da funcionalidade', max_length=100)),
                ('body_json', models.JSONField(default=list, help_text='Lista de strings (parágrafos).')),
                ('cta_label', models.CharField(help_text='Texto do botão CTA', max_length=100)),
                ('cta_url', models.URLField(help_text='URL do botão CTA')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0, help_text='Quantidade de destinatários no envio.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_campaigns_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campanha de email de funcionalidade',
                'verbose_name_plural': 'Campanhas de email de funcionalidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Erro em caso de falha no envio.')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.featureemailcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de email de funcionalidade',
                'verbose_name_plural': 'Logs de email de funcionalidade',
                'ordering': ['-sent_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
