# Generated by Django 6.0.4 on 2026-08-14 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_add_feature_email_campaign_and_log_mvp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lesson_alert_threshold',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Avisar quando faltarem N aulas para o pacote acabar. Vazio usa o padrão do professor.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lesson_alert_default',
            field=models.PositiveSmallIntegerField(default=2, help_text='Padrão: avisar quando faltarem N aulas para o pacote acabar', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lesson_alert_enabled',
            field=models.BooleanField(default=True, help_text='Avisar quando o pacote de aulas de um aluno estiver acabando'),
        ),
    ]
