# Generated by Django 6.0.4 on 2026-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_lembrete_fim_de_pacote'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cpf_cnpj_is_pix',
            field=models.BooleanField(default=False, help_text='O CPF/CNPJ acima também é a chave Pix'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave Pix, quando for diferente do CPF/CNPJ', max_length=255),
        ),
    ]
