# Generated by Django 6.0.4 on 2026-08-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_lembrete_fim_de_pacote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(blank=True, help_text='ID da WhatsApp Business Account do cliente', max_length=64)),
                ('phone_number_id', models.CharField(help_text='ID do número na Cloud API. É por aqui que o webhook acha a conta.', max_length=64, unique=True)),
                ('business_id', models.CharField(blank=True, help_text='ID do Business Manager do cliente', max_length=64)),
                ('display_phone_number', models.CharField(blank=True, help_text='Número como a Meta devolve, ex.: +55 41 98836-9627', max_length=32)),
                ('verified_name', models.CharField(blank=True, help_text='Nome de exibição aprovado pela Meta', max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True, help_text='Token de acesso cifrado. Não expor em API nem em log.')),
                ('is_coexistence', models.BooleanField(default=True, help_text='Número também ativo no aplicativo do celular. Mensagens enviadas por lá chegam como echo e não passam pela janela de 24h.')),
                ('is_active', models.BooleanField(default=False, help_text='Interruptor por conta. Desligado, o sistema não envia nada.')),
                ('status', models.CharField(choices=[('pending', 'Aguardando conexão'), ('connected', 'Conectado'), ('error', 'Com erro'), ('disconnected', 'Desconectado')], default='pending', max_length=20)),
                ('quality_rating', models.CharField(blank=True, help_text='GREEN, YELLOW ou RED. Cai quando os destinatários denunciam.', max_length=20)),
                ('messaging_limit', models.CharField(blank=True, help_text='Tier de envio da Meta, ex.: TIER_1K', max_length=32)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Professor dono da conta (a escola). Parceiros usam o número dele.', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta WhatsApp',
                'verbose_name_plural': 'Contas WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="Identificador da Meta, E.164 sem '+'. No Brasil pode vir sem o nono dígito.", max_length=32)),
                ('phone_e164', models.CharField(blank=True, help_text='Número normalizado com o nono dígito, para casar com o cadastro.', max_length=32)),
                ('profile_name', models.CharField(blank=True, help_text='Nome que a pessoa usa no WhatsApp', max_length=255)),
                ('relationship', models.CharField(choices=[('unknown', 'Não identificado'), ('student', 'Aluno'), ('guardian', 'Responsável'), ('lead', 'Interessado'), ('other', 'Outro')], default='unknown', max_length=20)),
                ('opt_in_status', models.CharField(choices=[('pending', 'Não perguntado'), ('granted', 'Aceitou receber'), ('revoked', 'Pediu para parar')], default='pending', max_length=20)),
                ('opt_in_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_source', models.CharField(blank=True, help_text='Onde o consentimento foi dado: contrato, matrícula, resposta no WhatsApp...', max_length=100)),
                ('is_blocked', models.BooleanField(default=False, help_text='Não enviar nada para este número, em nenhuma circunstância.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.whatsappaccount')),
                ('student', models.ForeignKey(blank=True, help_text='Aluno ligado a este número. Um aluno pode ter mãe e pai separados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_contacts', to='core.student')),
            ],
            options={
                'verbose_name': 'Contato WhatsApp',
                'verbose_name_plural': 'Contatos WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_inbound_at', models.DateTimeField(blank=True, help_text='Última mensagem recebida. É o que abre a janela de 24h.', null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.whatsappaccount')),
                ('assigned_teacher', models.ForeignKey(blank=True, help_text='Professor responsável. Herdado de Student.assigned_teacher, com o dono da conta como padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to=settings.AUTH_USER_MODEL)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='core.whatsappcontact')),
            ],
            options={
                'verbose_name': 'Conversa WhatsApp',
                'verbose_name_plural': 'Conversas WhatsApp',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome exato aprovado na Meta', max_length=255)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('category', models.CharField(choices=[('UTILITY', 'Utilidade'), ('MARKETING', 'Marketing'), ('AUTHENTICATION', 'Autenticação')], default='UTILITY', max_length=20)),
                ('purpose', models.CharField(choices=[('billing_friendly', 'Cobrança: lembrete amigável'), ('billing_due_today', 'Cobrança: vence hoje'), ('billing_overdue', 'Cobrança: em atraso'), ('billing_thank_you', 'Cobrança: agradecimento'), ('lesson_reminder', 'Lembrete de aula'), ('lesson_cancelled', 'Aula cancelada'), ('task_assigned', 'Tarefa enviada'), ('package_ending', 'Pacote de aulas acabando'), ('opt_in_request', 'Pedido de autorização para enviar mensagens'), ('other', 'Outro')], default='other', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Em análise'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Reprovado'), ('PAUSED', 'Pausado pela Meta'), ('DISABLED', 'Desativado')], default='PENDING', max_length=20)),
                ('body_text', models.TextField(blank=True, help_text='Corpo aprovado, com as chaves {{1}}, {{2}}...')),
                ('variable_hints', models.JSONField(blank=True, default=list, help_text="Descrição de cada variável, na ordem. Ex.: ['nome', 'valor', 'vencimento']")),
                ('rejected_reason', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(help_text='ID da mensagem na Meta. Garante idempotência do webhook.', max_length=128, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Recebida'), ('out', 'Enviada')], max_length=4)),
                ('origin', models.CharField(choices=[('api', 'Enviada pelo sistema'), ('app', 'Enviada pelo aplicativo do celular'), ('contact', 'Enviada pelo contato')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('received', 'Recebida')], default='queued', max_length=20)),
                ('message_type', models.CharField(default='text', help_text='text, image, audio, document, template...', max_length=30)),
                ('body', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=128)),
                ('media_mime', models.CharField(blank=True, max_length=100)),
                ('media_filename', models.CharField(blank=True, max_length=255)),
                ('media_file', models.FileField(blank=True, help_text='Cópia local. A URL da Meta expira e o anexo se perderia.', null=True, upload_to='whatsapp_media/%Y/%m/')),
                ('reply_to_wamid', models.CharField(blank=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(help_text='Hora da mensagem segundo a Meta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.billinglog')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.whatsappconversation')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.lesson')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Quem disparou pelo sistema. Vazio em echo do aplicativo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(help_text='Hash do conteúdo do evento. Ver whatsapp.webhook_event_key.', max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='core.whatsappaccount')),
            ],
            options={
                'verbose_name': 'Evento de webhook WhatsApp',
                'verbose_name_plural': 'Eventos de webhook WhatsApp',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['account', 'phone_e164'], name='core_whatsa_account_db03ed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['student'], name='core_whatsa_student_374e37_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsappcontact',
            unique_together={('account', 'wa_id')},
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['account', '-last_message_at'], name='core_whatsa_account_d5b6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['assigned_teacher', '-last_message_at'], name='core_whatsa_assigne_3bafdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='whatsapptemplate',
            unique_together={('account', 'name', 'language')},
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='core_whatsa_convers_7f6657_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessage',
            index=models.Index(fields=['status'], name='core_whatsa_status_52fa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhookevent',
            index=models.Index(fields=['-received_at'], name='core_whatsa_receive_b98aac_idx'),
        ),
    ]
