# Generated by Django 6.0.4 on 2026-08-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_userprofile_cpf_cnpj_is_pix_userprofile_pix_key'),
        ('core', '0057_whatsapp_business_cloud_api'),
    ]

    operations = [
    ]
