"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-unsafe")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # por enquanto, depois afinamos

# CSRF_TRUSTED_ORIGINS - permite domínios específicos para CSRF
# IMPORTANTE: Django não suporta wildcards (*), precisa ser domínio completo
# No Railway, o domínio pode variar, então vamos usar variável de ambiente
csrf_origins_str = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
else:
    # Domínios padrão (sem wildcards - Django não suporta)
    CSRF_TRUSTED_ORIGINS = [
        "https://cini-english-cini-english.up.railway.app",
        "https://www.educaflowone.com.br",
        "https://educaflowone.com.br",  # Sem www também
    ]

# Se estiver no Railway, adicionar o domínio atual automaticamente
railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN') or os.environ.get('RAILWAY_STATIC_URL')
if railway_domain:
    # Remove protocolo se presente e adiciona https://
    railway_domain = railway_domain.replace('https://', '').replace('http://', '')
    railway_origin = f"https://{railway_domain}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

# Adicionar também o domínio customizado do Railway se configurado
# O Railway pode ter múltiplos domínios, então adicionamos o customizado também
custom_domain = os.environ.get('RAILWAY_CUSTOM_DOMAIN') or os.environ.get('CUSTOM_DOMAIN')
if custom_domain:
    # Remove protocolo se presente e adiciona https://
    custom_domain = custom_domain.replace('https://', '').replace('http://', '')
    custom_origin = f"https://{custom_domain}"
    if custom_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(custom_origin)
    # Adicionar também versão sem www se for www
    if custom_domain.startswith('www.'):
        domain_without_www = custom_domain.replace('www.', '')
        origin_without_www = f"https://{domain_without_www}"
        if origin_without_www not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin_without_www)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "core",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# Configurações de CSRF
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'  # True em produção HTTPS
CSRF_COOKIE_HTTPONLY = False  # Permite acesso via JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'  # Compatível com requisições cross-site controladas
CSRF_USE_SESSIONS = False  # Usa cookies (padrão)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend" / "templates"],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


#DATABASES = {
#    'default': dj_database_url.config(
#        default=os.environ.get("DATABASE_URL"),
#        conn_max_age=600,
#        ssl_require=True
#    )
#}


DB_NAME = os.getenv("DB_NAME", "cini_english")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASS", "masterkey")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")

DATABASES = {
    "default": dj_database_url.config(
        default=f"postgres://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
        conn_max_age=600,
    )
}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "templates",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Redireciona para login quando não autenticado
LOGIN_URL = "/login/"
# Pós-login: / leva à HomeView que, se autenticado, redireciona para dashboard/planos/calendar
LOGIN_REDIRECT_URL = "/"
# Pós-logout: ir para tela de login
LOGOUT_REDIRECT_URL = "/login/"

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

# Email configuration
# Se não houver credenciais configuradas, usa console backend (para desenvolvimento)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Produção: usar SMTP real
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    # Tentar porta 465 (SSL) primeiro, que é mais compatível com cloud providers
    # Se não funcionar, pode tentar 587 (TLS) via variável de ambiente
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
    # Porta 465 usa SSL, porta 587 usa TLS
    if EMAIL_PORT == 465:
        EMAIL_USE_SSL = True
        EMAIL_USE_TLS = False
    else:
        EMAIL_USE_SSL = False
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@educaflowone.com')
    # Timeout de 10 segundos para evitar que email bloqueie a resposta HTTP
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
    print(f"✅ EMAIL: Configurado para SMTP real")
    print(f"   Host: {EMAIL_HOST}:{EMAIL_PORT}")
    print(f"   From: {DEFAULT_FROM_EMAIL}")
    print(f"   SSL: {EMAIL_USE_SSL if EMAIL_PORT == 465 else False}")
    print(f"   TLS: {EMAIL_USE_TLS if EMAIL_PORT != 465 else False}")
    print(f"   Timeout: {EMAIL_TIMEOUT}s")
else:
    # Desenvolvimento: usar console backend (imprime no terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@educaflowone.com')
    print("⚠️  EMAIL: Usando console backend (desenvolvimento). Configure EMAIL_HOST_USER e EMAIL_HOST_PASSWORD para envio real.")

# Support email
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'jonasbarros98@gmail.com')

