"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import json
import os
from dotenv import load_dotenv
load_dotenv()
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-secret-unsafe")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]  # por enquanto, depois afinamos

# CSRF_TRUSTED_ORIGINS - permite domínios específicos para CSRF
# IMPORTANTE: Django não suporta wildcards (*), precisa ser domínio completo
# No Railway, o domínio pode variar, então vamos usar variável de ambiente
csrf_origins_str = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_str:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_str.split(',') if origin.strip()]
else:
    # Domínios padrão (sem wildcards - Django não suporta)
    CSRF_TRUSTED_ORIGINS = [
        "https://cini-english-cini-english.up.railway.app",
        "https://www.educaflowone.com.br",
        "https://educaflowone.com.br",  # Sem www também
    ]

# Se estiver no Railway, adicionar o domínio atual automaticamente
railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN') or os.environ.get('RAILWAY_STATIC_URL')
if railway_domain:
    # Remove protocolo se presente e adiciona https://
    railway_domain = railway_domain.replace('https://', '').replace('http://', '')
    railway_origin = f"https://{railway_domain}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

# Adicionar também o domínio customizado do Railway se configurado
# O Railway pode ter múltiplos domínios, então adicionamos o customizado também
custom_domain = os.environ.get('RAILWAY_CUSTOM_DOMAIN') or os.environ.get('CUSTOM_DOMAIN')
if custom_domain:
    # Remove protocolo se presente e adiciona https://
    custom_domain = custom_domain.replace('https://', '').replace('http://', '')
    custom_origin = f"https://{custom_domain}"
    if custom_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(custom_origin)
    # Adicionar também versão sem www se for www
    if custom_domain.startswith('www.'):
        domain_without_www = custom_domain.replace('www.', '')
        origin_without_www = f"https://{domain_without_www}"
        if origin_without_www not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin_without_www)

# ── Reverse proxy (Railway, Nginx, etc.) ─────────────────────────────
# Sem isso, request.build_absolute_uri() vira http://... atrás do TLS do proxy,
# o Sign in with Google envia redirect_uri em HTTP e o Google retorna Erro 400:
# redirect_uri_mismatch (no Console só está registrado https://...).
# Railway envia X-Forwarded-Proto: https (e costuma enviar X-Forwarded-Host).
_on_railway = any(
    os.environ.get(k)
    for k in ("RAILWAY_ENVIRONMENT", "RAILWAY_PROJECT_ID", "RAILWAY_SERVICE_ID")
)
_trust_proxy = os.environ.get("TRUST_PROXY_SSL", "").strip().lower() in ("1", "true", "yes", "on")
if _on_railway or _trust_proxy:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "core",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

# Configurações de CSRF
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'False').lower() == 'true'  # True em produção HTTPS
CSRF_COOKIE_HTTPONLY = False  # Permite acesso via JavaScript
CSRF_COOKIE_SAMESITE = 'Lax'  # Compatível com requisições cross-site controladas
CSRF_USE_SESSIONS = False  # Usa cookies (padrão)

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend" / "templates"],
        'APP_DIRS': True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.trial_banner",
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


#DATABASES = {
#    'default': dj_database_url.config(
#        default=os.environ.get("DATABASE_URL"),
#        conn_max_age=600,
#        ssl_require=True
#    )
#}


DB_NAME = os.getenv("DB_NAME", "cini_english")
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASS = os.getenv("DB_PASS", "masterkey")
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")

DATABASES = {
    "default": dj_database_url.config(
        default=f"postgres://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
        conn_max_age=600,
    )
}




# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "frontend" / "templates",
]
# WhiteNoise com manifest exige `collectstatic` (inclui core/static, ex.: img/educaflow-new.png).
# Local: defina DJANGO_STATICFILES_SIMPLE=1 para servir sem manifest, ou rode: python manage.py collectstatic
if os.environ.get("DJANGO_STATICFILES_SIMPLE", "").lower() in ("1", "true", "yes"):
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise + manifest: com manifest_strict=True (Django default), qualquer {% static %}
# sem entrada em staticfiles.json após collectstatic quebra o request (500 em massa).
# Só ativar strict explicitamente: WHITENOISE_MANIFEST_STRICT=1
WHITENOISE_MANIFEST_STRICT = os.environ.get(
    "WHITENOISE_MANIFEST_STRICT", ""
).strip().lower() in ("1", "true", "yes")

# Django 4.2+ usa só STORAGES (STATICFILES_STORAGE sozinho não substitui "staticfiles").
# Se STORAGES só for definido com USE_R2_STORAGE=True, o `collectstatic` no Docker build
# — onde R2 costuma estar desligado — gera ficheiros sem manifest; em runtime com R2
# o backend passa a ser CompressedManifestStaticFilesStorage e o CSS/imagens deixam de bater.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": STATICFILES_STORAGE,
    },
}

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Persistência de uploads no Railway (PRD):
# - Postgres persiste apenas metadados (caminho/nome do arquivo), não os bytes.
# - Em produção (Railway), o disco local pode ser efêmero.
# - Portanto, quando `USE_R2_STORAGE=true`, usamos storage compatível com S3 (Cloudflare R2)
#   via `django-storages` para que os bytes persistam fora do container.
USE_R2_STORAGE = os.environ.get("USE_R2_STORAGE", "").lower() in ("1", "true", "yes")

if USE_R2_STORAGE:
    # Cloudflare R2 usa credenciais S3 + endpoint customizado.
    # No Railway, configure as variáveis: R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME e R2_ENDPOINT_URL.
    AWS_ACCESS_KEY_ID = os.environ.get("R2_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = os.environ.get("R2_SECRET_ACCESS_KEY", "")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("R2_BUCKET_NAME", "")
    AWS_S3_ENDPOINT_URL = os.environ.get("R2_ENDPOINT_URL", "")

    # Alguns setups exigem uma região "fake" (não é usada pelo R2).
    AWS_S3_REGION_NAME = os.environ.get("R2_REGION_NAME", "auto")

    # Cloudflare R2 costuma funcionar melhor com addressing estilo "path".
    AWS_S3_ADDRESSING_STYLE = os.environ.get("R2_S3_ADDRESSING_STYLE", "path")
    AWS_S3_SIGNATURE_VERSION = os.environ.get("R2_S3_SIGNATURE_VERSION", "s3v4")

    # Endereço/URL gerados pelo storage: por padrão usamos URL assinada.
    AWS_QUERYSTRING_AUTH = True
    AWS_DEFAULT_ACL = None

    # Garante que o cache/etag faça sentido em downloads.
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": os.environ.get("R2_CACHE_CONTROL", "max-age=86400"),
    }

    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    }

    # Diagnóstico no Railway: confirmar que o backend de storage R2/S3 está ativo.
    # (Não imprime secrets; ajuda a verificar "por que o bucket ficou vazio".)
    print(
        "[R2] ENABLED",
        f"bucket={AWS_STORAGE_BUCKET_NAME}",
        f"endpoint={AWS_S3_ENDPOINT_URL}",
        f"addressing={AWS_S3_ADDRESSING_STYLE}",
        f"access_key_set={bool(AWS_ACCESS_KEY_ID)}",
        f"secret_key_set={bool(AWS_SECRET_ACCESS_KEY)}",
    )

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Redireciona para login quando não autenticado
LOGIN_URL = "/login/"
# Pós-login: / leva à HomeView que, se autenticado, redireciona para dashboard/planos/calendar
LOGIN_REDIRECT_URL = "/"
# Pós-logout: ir para tela de login
LOGOUT_REDIRECT_URL = "/login/"

# Session configuration
SESSION_COOKIE_AGE = 86400  # 24 horas
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_SAVE_EVERY_REQUEST = True

# Email configuration
# Prioridade: RESEND_API_KEY (funciona no Railway Free/Hobby, SMTP é bloqueado) > SMTP Gmail
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if RESEND_API_KEY:
    # Resend via API HTTPS - funciona em qualquer plano do Railway (porta 443 não é bloqueada)
    EMAIL_BACKEND = 'anymail.backends.resend.EmailBackend'
    ANYMAIL = {'RESEND_API_KEY': RESEND_API_KEY}
    # Resend exige domínio verificado; use DEFAULT_FROM_EMAIL com email do domínio que você adicionou no painel Resend
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'contato@educaflowone.com.br')
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
    print("[OK] EMAIL: Configurado para Resend (API)")
    print(f"   From: {DEFAULT_FROM_EMAIL}")
elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Produção: usar SMTP real
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    # Tentar porta 465 (SSL) primeiro, que é mais compatível com cloud providers
    # Se não funcionar, pode tentar 587 (TLS) via variável de ambiente
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))
    # Porta 465 usa SSL, porta 587 usa TLS
    if EMAIL_PORT == 465:
        EMAIL_USE_SSL = True
        EMAIL_USE_TLS = False
    else:
        EMAIL_USE_SSL = False
        EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@educaflowone.com')
    # Timeout de 10 segundos para evitar que email bloqueie a resposta HTTP
    EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
    print(f"[OK] EMAIL: Configurado para SMTP real")
    print(f"   Host: {EMAIL_HOST}:{EMAIL_PORT}")
    print(f"   From: {DEFAULT_FROM_EMAIL}")
    print(f"   SSL: {EMAIL_USE_SSL if EMAIL_PORT == 465 else False}")
    print(f"   TLS: {EMAIL_USE_TLS if EMAIL_PORT != 465 else False}")
    print(f"   Timeout: {EMAIL_TIMEOUT}s")
else:
    # Desenvolvimento: usar console backend (imprime no terminal)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@educaflowone.com')
    print("[WARN] EMAIL: Usando console backend (desenvolvimento). Configure EMAIL_HOST_USER e EMAIL_HOST_PASSWORD para envio real.")

# Support email
SUPPORT_EMAIL = os.environ.get('SUPPORT_EMAIL', 'educaflowone@gmail.com')

# Landing page contact form (visitantes não logados)
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', 'educaflowone@gmail.com')

# Notificação interna: novo cadastro (envia via mesmo backend de email — Resend quando RESEND_API_KEY)
INTERNAL_SIGNUP_NOTIFY_ENABLED = os.environ.get('INTERNAL_SIGNUP_NOTIFY_ENABLED', 'true').strip().lower() in (
    '1', 'true', 'yes', 'on',
)
INTERNAL_SIGNUP_NOTIFY_TO = os.environ.get('INTERNAL_SIGNUP_NOTIFY_TO', 'educaflowone@gmail.com').strip()
# Vários CC separados por vírgula
INTERNAL_SIGNUP_NOTIFY_CC = os.environ.get(
    'INTERNAL_SIGNUP_NOTIFY_CC',
    'jonasbarros98@gmail.com',
).strip()

# URL base do site (para links em emails - login, etc.)
SITE_URL = os.environ.get('SITE_URL', 'https://www.educaflowone.com.br')


def _norm_oauth_client_id(s: str) -> str:
    s = (s or '').strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in '"\'':
        s = s[1:-1].strip()
    # Remove qualquer whitespace (quebra de linha no Railway / colagem do Console)
    s = ''.join(s.split())
    return s


def _resolve_google_oauth_client_id() -> str:
    """
    Client ID OAuth (app Web) para Sign in with Google.
    Preferir GOOGLE_OAUTH_CLIENT_ID=xxx.apps.googleusercontent.com
    Alternativa: ID_JSON_GOOGLE_CLOUD = caminho absoluto ou relativo à raiz do projeto
    (ex.: docs/google/client_secret_....json) para o JSON do Google Cloud,
    ou string JSON com chave "web"/"installed" e client_id.
    """
    cid = _norm_oauth_client_id(os.environ.get('GOOGLE_OAUTH_CLIENT_ID', ''))
    if cid:
        return cid
    raw = os.environ.get('ID_JSON_GOOGLE_CLOUD', '').strip()
    if not raw:
        return ''
    try:
        if raw.startswith('{'):
            data = json.loads(raw)
        else:
            p = Path(raw)
            if not p.is_file() and not p.is_absolute():
                alt = BASE_DIR / raw
                if alt.is_file():
                    p = alt
            if p.is_file():
                data = json.loads(p.read_text(encoding='utf-8'))
            elif '.apps.googleusercontent.com' in raw:
                return raw
            else:
                return ''
        web = data.get('web') or data.get('installed')
        if not web:
            return ''
        return _norm_oauth_client_id(web.get('client_id') or '')
    except Exception:
        return ''


GOOGLE_OAUTH_CLIENT_ID = _resolve_google_oauth_client_id()

# Assinatura dos emails automáticos (boas-vindas, etc). Use \\n para quebras de linha.
EMAIL_SIGNATURE = os.environ.get('EMAIL_SIGNATURE', '''—
Equipe EducaflowOne
Plataforma de gestão para professores particulares

🌐 https://www.educaflowone.com.br

📧 educaflowone@gmail.com

📱 WhatsApp: (41) 99239-4289

Organize alunos, aulas e pagamentos em um só lugar.''').replace('\\n', '\n')

